import { FILENAME_PASCALCASE } from '../constants';
import { Snippet } from '../types';

export const tsNextGSS: Snippet = {
  prefix: ['nxGSS', 'getServerSideProps'],
  body: [
    "import { GetServerSidePropsContext, GetServerSidePropsResult } from 'next'",
    '',
    'type Context = GetServerSidePropsContext',
    'type Result = GetServerSidePropsResult<{ ${1:data}: any }>',
    '',
    'export async function getServerSideProps(ctx: Context): Promise<Result> {',
    '\tconst { ${2:req, res, params, query} } = ctx',
    '\t$0',
    '\treturn {',
    '\t\tprops: {',
    '\t\t\t$1: null,',
    '\t\t},',
    '\t}',
    '}',
    '',
  ],
  description: 'Next.js getServerSideProps',
};

export const tsNextGST: Snippet = {
  prefix: ['nxGST', 'getStaticProps'],
  body: [
    "import { GetStaticPropsContext, GetStaticPropsResult } from 'next'",
    '',
    'type Context = GetStaticPropsContext',
    'type Result = GetStaticPropsResult<{ ${1:data}: any }>',
    '',
    'export async function getStaticProps({ params }: Context): Promise<Result> {',
    '\t${0:// code}',
    '',
    '\treturn {',
    '\t\tprops: {',
    '\t\t\t$1: null,',
    '\t\t},',
    '\t}',
    '}',
    '',
  ],
  description: 'Next.js getStaticProps',
};

export const tsNextGSP: Snippet = {
  prefix: ['nxGSP', 'getStaticPaths'],
  body: [
    "import { GetStaticPathsResult } from 'next'",
    '',
    'export async function getStaticPaths(): Promise<GetStaticPathsResult> {',
    '\t${0:// code}',
    '',
    '\treturn {',
    '\t\tpaths: [],',
    "\t\tfallback: ${1|true,false,'blocking'|},",
    '\t}',
    '}',
    '',
  ],
  description: 'Next.js getStaticPaths',
};

export const tsNextPageGSS: Snippet = {
  prefix: 'nxpGSS',
  body: [
    "import { GetServerSidePropsContext, GetServerSidePropsResult } from 'next'",
    '',
    'type Context = GetServerSidePropsContext',
    'type Result = GetServerSidePropsResult<{ ${2:data}: any }>',
    '',
    'export async function getServerSideProps(ctx: Context): Promise<Result> {',
    '\tconst { ${3:req, res, params, query} } = ctx',
    '\t$0',
    '\treturn {',
    '\t\tprops: {',
    '\t\t\t$2: null,',
    '\t\t},',
    '\t}',
    '}',
    '',
    `export default function \${1:${FILENAME_PASCALCASE}Page}() {`,
    '\treturn (',
    '\t\t<>',
    '\t\t\t$1 content',
    '\t\t</>',
    '\t)',
    '}',
    '',
  ],
  description: 'Next.js page with getServerSideProps',
};

export const tsNextPageGST: Snippet = {
  prefix: 'nxpGST',
  body: [
    "import { GetStaticPropsContext, GetStaticPropsResult } from 'next'",
    '',
    'type Context = GetStaticPropsContext',
    'type Result = GetStaticPropsResult<{ ${2:data}: any }>',
    '',
    'export async function getStaticProps({ params }: Context): Promise<Result> {',
    '\t${0:// code}',
    '',
    '\treturn {',
    '\t\tprops: {',
    '\t\t\t$2: null,',
    '\t\t},',
    '\t}',
    '}',
    '',
    `export default function \${1:${FILENAME_PASCALCASE}Page}() {`,
    '\treturn (',
    '\t\t<>',
    '\t\t\t$1 content',
    '\t\t</>',
    '\t)',
    '}',
    '',
  ],
  description: 'Next.js page with getStaticProps',
};

export const tsNextGSSArrowFunction: Snippet = {
  prefix: ['nxaGSS', 'getServerSideProps'],
  body: [
    "import { GetServerSideProps } from 'next'",
    '',
    'export const getServerSideProps: GetServerSideProps<{ ${1:data}: any }> = async (ctx) => {',
    '\tconst { ${2:req, res, params, query} } = ctx',
    '\t$0',
    '\treturn {',
    '\t\tprops: {',
    '\t\t\t$1: null,',
    '\t\t},',
    '\t}',
    '}',
    '',
  ],
  description: 'Next.js getServerSideProps arrow function',
};

export const tsNextGSTArrowFunction: Snippet = {
  prefix: ['nxaGST', 'getStaticProps'],
  body: [
    "import { GetStaticProps } from 'next'",
    '',
    'export const getStaticProps: GetStaticProps<{ ${1:data}: any }> = async (ctx) => {',
    '\tconst { params } = ctx',
    '\t$0',
    '\treturn {',
    '\t\tprops: {',
    '\t\t\t$1: null,',
    '\t\t},',
    '\t}',
    '}',
    '',
  ],
  description: 'Next.js getStaticProps arrow function',
};

export const tsNextGSPArrowFunction: Snippet = {
  prefix: ['nxaGSP', 'getStaticPaths'],
  body: [
    "import { GetStaticPaths } from 'next'",
    '',
    'export const getStaticPaths: GetStaticPaths = async () => {',
    '\t${0:// code}',
    '',
    '\treturn {',
    '\t\tpaths: [],',
    "\t\tfallback: ${1|true,false,'blocking'|},",
    '\t}',
    '}',
    '',
  ],
  description: 'Next.js getStaticPaths arrow function',
};

export const tsNextPageGSSArrowFunction: Snippet = {
  prefix: 'nxpaGSS',
  body: [
    "import { GetServerSideProps } from 'next'",
    '',
    'export const getServerSideProps: GetServerSideProps<{ ${2:data}: any }> = async (ctx) => {',
    '\tconst { ${3:req, res, params, query} } = ctx',
    '\t$0',
    '\treturn {',
    '\t\tprops: {',
    '\t\t\t$2: null,',
    '\t\t},',
    '\t}',
    '}',
    '',
    `const \${1:${FILENAME_PASCALCASE}Page} = () => {`,
    '\treturn (',
    '\t\t<>',
    '\t\t\t$1 content',
    '\t\t</>',
    '\t)',
    '}',
    '',
    'export default $1',
    '',
  ],
  description: 'Next.js page with getServerSideProps',
};

export const tsNextPageGSTArrowFunction: Snippet = {
  prefix: 'nxpaGST',
  body: [
    "import { GetStaticProps } from 'next'",
    '',
    'export const getStaticProps: GetStaticProps<{ ${2:data}: any }> = async (ctx) => {',
    '\tconst { params } = ctx',
    '\t$0',
    '\treturn {',
    '\t\tprops: {',
    '\t\t\t$2: null,',
    '\t\t},',
    '\t}',
    '}',
    '',
    `const \${1:${FILENAME_PASCALCASE}Page} = () => {`,
    '\treturn (',
    '\t\t<>',
    '\t\t\t$1 content',
    '\t\t</>',
    '\t)',
    '}',
    '',
    'export default $1',
    '',
  ],
  description: 'Next.js page with getStaticProps',
};
